name: gymcrm-demo

services:
  activemq:
    image: apache/activemq-classic:6.1.7
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - gymcrm-net

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - gymcrm-net

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - gymcrm-net

  gymcrm-main:
    image: gymcrm-main:local
    container_name: gymcrm-main
    build:
      context: ./GymCRM
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
    depends_on:
      - activemq
      - postgres
    networks:
      - gymcrm-net

  gymcrm-report:
    image: gymcrm-report:local
    container_name: gymcrm-report
    build:
      context: ./GymCRM-workload
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
      SPRING_AUTOCONFIGURE_EXCLUDE: de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: "27017"
      SPRING_DATA_MONGODB_DATABASE: gymcrm
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: admin
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
    depends_on:
      - activemq
      - mongodb
    networks:
      - gymcrm-net

networks:
  gymcrm-net:
    driver: bridge
